version: "3"

services:
  php:
    image: php:7.4-apache
    container_name: meu-php
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - /home/coimbra/php:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: meu-mysql-php
    ports:
      - "3310:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
