version: "3.7"

services:
  # image project
  php:
    container_name: php-basico
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-network

  # nginx
  nginx:
    container_name: nginx-basico
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8585:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-network

  #mysql
  mysql:
    container_name: setup-mysql-basico
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - setup-network

  #phpmyadmin
  phpmyadmin:
    container_name: setup-phpmyadmin-basico
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8282:80"
    environment:
      PMA_HOST: setup-mysql-basico
    depends_on:
      - mysql
    networks:
      - setup-network
networks:
  setup-network:
    driver: bridge
